kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: redis-insight-ingress
  namespace: redis
  annotations:
    nginx.ingress.kubernetes.io/compress-types: "text/css application/javascript application/json"
    nginx.ingress.kubernetes.io/compress-enable: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 50m
    nginx.ingress.kubernetes.io/proxy-max-temp-file-size: 50m
    nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
spec:
  ingressClassName: nginx
  rules:
    - host: dv-mon-ri.dwl.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: redisinsight-service
                port:
                  number: 80
