apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafbat-ui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
    notifications.argoproj.io/subscribe.on-deployed.slack: ea-cloud-argo-cd-status
    notifications.argoproj.io/subscribe.on-health-degraded.slack: ea-cloud-argo-cd-status
    notifications.argoproj.io/subscribe.on-sync-failed.slack: ea-cloud-argo-cd-status
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  project: default
  source:
    chart: kafka-ui
    repoURL: https://ui.charts.kafbat.io
    targetRevision: 1.5.1
    helm:
      valuesObject:
        yamlApplicationConfig:
          kafka:
            clusters:
              - name: local
                bootstrapServers:  kafka:9092
                properties:
                  security.protocol: SASL_PLAINTEXT
                  sasl.mechanism: PLAIN
        service:
            type: NodePort
            nodePort: 31841
            port: 80
            targetPort: http
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
