apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
    notifications.argoproj.io/subscribe.on-deployed.slack: ea-cloud-argo-cd-status
    notifications.argoproj.io/subscribe.on-health-degraded.slack: ea-cloud-argo-cd-status
    notifications.argoproj.io/subscribe.on-sync-failed.slack: ea-cloud-argo-cd-status
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: fluent-bit
  project: default
  source:
    chart: fluent-bit
    repoURL: https://fluent.github.io/helm-charts
    targetRevision: 0.50.0
    helm:
      valuesObject:
        # env:
        #   - name: NODE_IP
        #     valueFrom:
        #       fieldRef:
        #         fieldPath: status.hostIP
        # hostNetwork: true
        # dnsPolicy: ClusterFirstWithHostNet
        existingConfigMap: "fluent-bit-config"
        # Mount writable paths used by your config
        extraVolumes:
          - name: fluentbit-state
            emptyDir: {}
          - name: fluentbit-buffers
            emptyDir:
              sizeLimit: 1Gi
          # - name: varlog-containers
          #   hostPath:
          #     path: /var/log/containers
          # - name: varlog-pods
          #   hostPath:
          #     path: /var/log/pods

        extraVolumeMounts:
          - name: fluentbit-state
            mountPath: /fluent-bit/state
          - name: fluentbit-buffers
            mountPath: /buffers
          # - name: varlog-containers
          #   mountPath: /var/log/containers
          #   readOnly: true
          # - name: varlog-pods
          #   mountPath: /var/log/pods
          #   readOnly: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
