apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
    notifications.argoproj.io/subscribe.on-deployed.slack: ea-cloud-argo-cd-status
    notifications.argoproj.io/subscribe.on-health-degraded.slack: ea-cloud-argo-cd-status
    notifications.argoproj.io/subscribe.on-sync-failed.slack: ea-cloud-argo-cd-status
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    chart: promtail
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.17.0
    helm:
      valuesObject:
        daemonset:
          enabled: false
        deployment:
          enabled: true
        extraArgs:
          - "-config.expand-env=true"
        extraEnvFrom:
          - secretRef:
              name: promtail-kafka-secret
        config:
          clients:
            - url: http://loki:3100/loki/api/v1/push
          snippets:
            scrapeConfigs: |
              - job_name: kafka-logs
                kafka:
                  assignor: sticky
                  use_incoming_timestamp: true
                  brokers:
                    - kafka-controller-headless.default:9092
                  group_id: "promtail-logs"
                  topics:
                    - k8s-logs
                  labels:
                    job: kafka-logs
                    topic: k8s-logs
                  authentication:
                    type: sasl
                    sasl_config:
                      mechanism: PLAIN
                      user: user1
                      password: ${KAFKA_PASSWORD}
                pipeline_stages:
                  - json:
                      expressions:
                        level: level
                        msg: log
                        ts: time
                        trace_id: trace_id
                        span_id: span_id
                        namespace: kubernetes.namespace_name
                        pod: kubernetes.pod_name
                        app: kubernetes.labels.app
                  - labels:
                      app:
                      namespace:
                      pod:
                      level:
                      trace_id:
                      span_id:
                  - timestamp:
                      source: ts
                      format: RFC3339Nano
                  - output:
                      source: msg
              - job_name: kafka-events
                kafka:
                  assignor: sticky
                  use_incoming_timestamp: true
                  brokers:
                    - kafka-controller-headless.default:9092
                  group_id: "promtail-event"
                  topics:
                    - k8s-events
                  labels:
                    job: kafka-events
                    topic: k8s-events
                  authentication:
                    type: sasl
                    sasl_config:
                      mechanism: PLAIN
                      user: user1
                      password: ${KAFKA_PASSWORD}
                pipeline_stages:
                  - json:
                      expressions:
                        level: level
                        msg: log
                        ts: time
                  - labels:
                      level:
                  - timestamp:
                      source: ts
                      format: RFC3339Nano
                  - output:
                      source: msg
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
